name: CI/CD with SonarQube and Deployment

on:
  push:
    branches:
      - main

jobs:
  build-test-sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Generate Coverage Report
        run: |
          npm install --save-dev jest
          npx jest --coverage

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          host: ${{ secrets.SONAR_HOST_URL }}
          login: ${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_SCANNER_OPTS: "-Dsonar.projectKey=your_project_key"
          NODE_ENV: "test"

  deploy:
    needs: build-test-sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-demo-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-demo-app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <AppServiceName>
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKER_USERNAME }}/ci-demo-app:latest
